### ISSUE TITLE
Results cannot be scrolled on FF

### ISSUE THREAD

**Issue by dennwc** [cayleygraph/web#7]
When there are too many results, the result panel cannot be scrolled with a mouse wheel when using Firefox (tested on 69.0.1 and 70.0b12). It works perfectly fine in Chrome. Scrolling with mouse by dragging the scroll bar works on FF as well.

**Comment by iddan** [comment]
Fixed by https://github.com/microsoft/monaco-editor/releases/tag/v0.18.1
